# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Zhantong Qiu
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# CMake script: Verify CSV file has content beyond header
#
# Purpose:
#   Validates that the CSV file generated by the IRBBLabel pass contains
#   actual data rows, not just the header line. This ensures the pass
#   successfully processed and labeled basic blocks.
#
# Usage:
#   cmake -DCSV_FILE=/path/to/bb_info.csv -P verify_csv.cmake
#
# Validation checks:
#   1. CSV file exists
#   2. CSV has at least 2 lines (header + at least one data row)
#
# Exit codes:
#   0: Validation passed (CSV has content)
#   1: Validation failed (file missing or only header)
#
# Called by:
#   Test CMakeLists.txt files in test*_csv_has_content tests

if(NOT EXISTS ${CSV_FILE})
    message(FATAL_ERROR "CSV file does not exist: ${CSV_FILE}")
endif()

# Read all lines from CSV file
file(STRINGS ${CSV_FILE} CSV_LINES)
list(LENGTH CSV_LINES LINE_COUNT)

# Require at least 2 lines: header + 1 data row
# (Even empty functions have entry block, so should always have data)
if(LINE_COUNT LESS 2)
    message(FATAL_ERROR "CSV file has no data rows (only header or empty). Lines: ${LINE_COUNT}")
endif()

message(STATUS "CSV file has ${LINE_COUNT} lines (including header)")
message(STATUS "✓ CSV verification passed")
